workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Capacitor Setup
        script: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          chmod +x android/gradlew
          npx cap sync
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk

  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Capacitor Setup
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          npx cap sync
      - name: Build iOS App
        script: |
          cd ios/App && xcodebuild -workspace App.xcworkspace -scheme App -configuration Release archive -archivePath $CM_BUILD_DIR/App.xcarchive
    artifacts:
      - $CM_BUILD_DIR/App.xcarchive
